//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfArgusOnline
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfArgusOnline.ArgusWSSoap")]
    public interface ArgusWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPluginInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.ExcelAddinVerInfo> GetPluginInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetCustomReportAsync(string authToken, WcfArgusOnline.PriceReportParams pars);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdatedPricesInDateTimeRange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetUpdatedPricesInDateTimeRangeAsync(string authToken, System.DateTime fromDateTime, System.DateTime toDateTime, decimal startId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomReportBin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.GetCustomReportBinResponse> GetCustomReportBinAsync(WcfArgusOnline.GetCustomReportBinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.AuthenticationResult> AuthenticateAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.AuthenticationResult> Authenticate2Async(string username, string password, string pluginInstallID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.AuthenticationResult> Authenticate3Async(string username, string password, string pluginInstallID, string pluginVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTablesBin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.GetTablesBinResponse> GetTablesBinAsync(WcfArgusOnline.GetTablesBinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTables", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetTablesAsync(string authToken, string[] tableNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTablesLastUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetTablesLastUpdatedAsync(string authToken, string[] tableNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<decimal[]> GetNewsListAsync(string authToken, System.DateTime dateFrom, System.DateTime dateTo, decimal[] categoryList, bool categoryiesListOr, decimal[] regionList, bool regionListOr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsStory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.NewsRecord> GetNewsStoryAsync(string authToken, decimal newsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsStoryById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.NewsRecordFull> GetNewsStoryByIdAsync(string authToken, decimal newsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewsItemsByDateTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WcfArgusOnline.GetNewsItemsByDateTimeResponse> GetNewsItemsByDateTimeAsync(WcfArgusOnline.GetNewsItemsByDateTimeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcelAddinVerInfo
    {
        
        private string latestVersionField;
        
        private string latestVersionUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LatestVersion
        {
            get
            {
                return this.latestVersionField;
            }
            set
            {
                this.latestVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LatestVersionUrl
        {
            get
            {
                return this.latestVersionUrlField;
            }
            set
            {
                this.latestVersionUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NewsEntity
    {
        
        private decimal newsIdField;
        
        private string headlineField;
        
        private System.DateTime publicationDateField;
        
        private System.DateTime dateModifiedField;
        
        private bool freeField;
        
        private bool featuredField;
        
        private decimal languageIdField;
        
        private decimal newsTypeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal NewsId
        {
            get
            {
                return this.newsIdField;
            }
            set
            {
                this.newsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Headline
        {
            get
            {
                return this.headlineField;
            }
            set
            {
                this.headlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime PublicationDate
        {
            get
            {
                return this.publicationDateField;
            }
            set
            {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DateModified
        {
            get
            {
                return this.dateModifiedField;
            }
            set
            {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Free
        {
            get
            {
                return this.freeField;
            }
            set
            {
                this.freeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Featured
        {
            get
            {
                return this.featuredField;
            }
            set
            {
                this.featuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal LanguageId
        {
            get
            {
                return this.languageIdField;
            }
            set
            {
                this.languageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal NewsTypeId
        {
            get
            {
                return this.newsTypeIdField;
            }
            set
            {
                this.newsTypeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NewsRecordFullCategories
    {
        
        private decimal[] regionIdsField;
        
        private decimal[] sectorIdsField;
        
        private decimal[] contextIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CategoryId", IsNullable=false)]
        public decimal[] RegionIds
        {
            get
            {
                return this.regionIdsField;
            }
            set
            {
                this.regionIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CategoryId", IsNullable=false)]
        public decimal[] SectorIds
        {
            get
            {
                return this.sectorIdsField;
            }
            set
            {
                this.sectorIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CategoryId", IsNullable=false)]
        public decimal[] ContextIds
        {
            get
            {
                return this.contextIdsField;
            }
            set
            {
                this.contextIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NewsRecordFull
    {
        
        private decimal newsIdField;
        
        private NewsRecordFullCategories categoryIdsField;
        
        private decimal[] streamIdsField;
        
        private bool freeField;
        
        private bool featuredField;
        
        private decimal languageIdField;
        
        private decimal newsTypeIdField;
        
        private string headlineField;
        
        private System.DateTime publicationDateField;
        
        private System.DateTime dateModifiedField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal NewsId
        {
            get
            {
                return this.newsIdField;
            }
            set
            {
                this.newsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NewsRecordFullCategories CategoryIds
        {
            get
            {
                return this.categoryIdsField;
            }
            set
            {
                this.categoryIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("StreamId", IsNullable=false)]
        public decimal[] StreamIds
        {
            get
            {
                return this.streamIdsField;
            }
            set
            {
                this.streamIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Free
        {
            get
            {
                return this.freeField;
            }
            set
            {
                this.freeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Featured
        {
            get
            {
                return this.featuredField;
            }
            set
            {
                this.featuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal LanguageId
        {
            get
            {
                return this.languageIdField;
            }
            set
            {
                this.languageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal NewsTypeId
        {
            get
            {
                return this.newsTypeIdField;
            }
            set
            {
                this.newsTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Headline
        {
            get
            {
                return this.headlineField;
            }
            set
            {
                this.headlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime PublicationDate
        {
            get
            {
                return this.publicationDateField;
            }
            set
            {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime DateModified
        {
            get
            {
                return this.dateModifiedField;
            }
            set
            {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NewsRecord
    {
        
        private decimal storyIdField;
        
        private decimal[] categoryIdsField;
        
        private string headlineField;
        
        private System.DateTime publicationDateField;
        
        private System.DateTime dateModifiedField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal StoryId
        {
            get
            {
                return this.storyIdField;
            }
            set
            {
                this.storyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public decimal[] CategoryIds
        {
            get
            {
                return this.categoryIdsField;
            }
            set
            {
                this.categoryIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Headline
        {
            get
            {
                return this.headlineField;
            }
            set
            {
                this.headlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime PublicationDate
        {
            get
            {
                return this.publicationDateField;
            }
            set
            {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateModified
        {
            get
            {
                return this.dateModifiedField;
            }
            set
            {
                this.dateModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationResult
    {
        
        private int loginResultField;
        
        private string authTokenField;
        
        private string latestVersionField;
        
        private string latestVersionUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LoginResult
        {
            get
            {
                return this.loginResultField;
            }
            set
            {
                this.loginResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AuthToken
        {
            get
            {
                return this.authTokenField;
            }
            set
            {
                this.authTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LatestVersion
        {
            get
            {
                return this.latestVersionField;
            }
            set
            {
                this.latestVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LatestVersionUrl
        {
            get
            {
                return this.latestVersionUrlField;
            }
            set
            {
                this.latestVersionUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PriceReportItem
    {
        
        private decimal quoteIdField;
        
        private decimal priceTypeIdField;
        
        private int priceReportItemIDField;
        
        private decimal forwardPeriodField;
        
        private decimal forwardYearField;
        
        private decimal currencyUnitField;
        
        private decimal measureUnitField;
        
        private decimal timestampIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal QuoteId
        {
            get
            {
                return this.quoteIdField;
            }
            set
            {
                this.quoteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal PriceTypeId
        {
            get
            {
                return this.priceTypeIdField;
            }
            set
            {
                this.priceTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PriceReportItemID
        {
            get
            {
                return this.priceReportItemIDField;
            }
            set
            {
                this.priceReportItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal ForwardPeriod
        {
            get
            {
                return this.forwardPeriodField;
            }
            set
            {
                this.forwardPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal ForwardYear
        {
            get
            {
                return this.forwardYearField;
            }
            set
            {
                this.forwardYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal CurrencyUnit
        {
            get
            {
                return this.currencyUnitField;
            }
            set
            {
                this.currencyUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal MeasureUnit
        {
            get
            {
                return this.measureUnitField;
            }
            set
            {
                this.measureUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal TimestampId
        {
            get
            {
                return this.timestampIdField;
            }
            set
            {
                this.timestampIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PriceReportParams
    {
        
        private EnPeriodicity periodicityField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private PriceReportItem[] itemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnPeriodicity Periodicity
        {
            get
            {
                return this.periodicityField;
            }
            set
            {
                this.periodicityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public PriceReportItem[] ItemList
        {
            get
            {
                return this.itemListField;
            }
            set
            {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnPeriodicity
    {
        
        /// <remarks/>
        Daily,
        
        /// <remarks/>
        Weekly,
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        Quarterly,
        
        /// <remarks/>
        Yearly,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomReportBin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomReportBinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string authToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public WcfArgusOnline.PriceReportParams pars;
        
        public GetCustomReportBinRequest()
        {
        }
        
        public GetCustomReportBinRequest(string authToken, WcfArgusOnline.PriceReportParams pars)
        {
            this.authToken = authToken;
            this.pars = pars;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomReportBinResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCustomReportBinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetCustomReportBinResult;
        
        public GetCustomReportBinResponse()
        {
        }
        
        public GetCustomReportBinResponse(byte[] GetCustomReportBinResult)
        {
            this.GetCustomReportBinResult = GetCustomReportBinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTablesBin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTablesBinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string authToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] tableNames;
        
        public GetTablesBinRequest()
        {
        }
        
        public GetTablesBinRequest(string authToken, string[] tableNames)
        {
            this.authToken = authToken;
            this.tableNames = tableNames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTablesBinResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTablesBinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetTablesBinResult;
        
        public GetTablesBinResponse()
        {
        }
        
        public GetTablesBinResponse(byte[] GetTablesBinResult)
        {
            this.GetTablesBinResult = GetTablesBinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNewsItemsByDateTime", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNewsItemsByDateTimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string authToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime dateTimeFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime dateTimeTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> free;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> featured;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> languageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> newsTypeId;
        
        public GetNewsItemsByDateTimeRequest()
        {
        }
        
        public GetNewsItemsByDateTimeRequest(string authToken, System.DateTime dateTimeFrom, System.DateTime dateTimeTo, System.Nullable<bool> free, System.Nullable<bool> featured, System.Nullable<decimal> languageId, System.Nullable<decimal> newsTypeId)
        {
            this.authToken = authToken;
            this.dateTimeFrom = dateTimeFrom;
            this.dateTimeTo = dateTimeTo;
            this.free = free;
            this.featured = featured;
            this.languageId = languageId;
            this.newsTypeId = newsTypeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNewsItemsByDateTimeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNewsItemsByDateTimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WcfArgusOnline.NewsEntity[] GetNewsItemsByDateTimeResult;
        
        public GetNewsItemsByDateTimeResponse()
        {
        }
        
        public GetNewsItemsByDateTimeResponse(WcfArgusOnline.NewsEntity[] GetNewsItemsByDateTimeResult)
        {
            this.GetNewsItemsByDateTimeResult = GetNewsItemsByDateTimeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ArgusWSSoapChannel : WcfArgusOnline.ArgusWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ArgusWSSoapClient : System.ServiceModel.ClientBase<WcfArgusOnline.ArgusWSSoap>, WcfArgusOnline.ArgusWSSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ArgusWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ArgusWSSoapClient.GetBindingForEndpoint(endpointConfiguration), ArgusWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArgusWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArgusWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArgusWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArgusWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArgusWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.ExcelAddinVerInfo> GetPluginInfoAsync()
        {
            return base.Channel.GetPluginInfoAsync();
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetCustomReportAsync(string authToken, WcfArgusOnline.PriceReportParams pars)
        {
            return base.Channel.GetCustomReportAsync(authToken, pars);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetUpdatedPricesInDateTimeRangeAsync(string authToken, System.DateTime fromDateTime, System.DateTime toDateTime, decimal startId)
        {
            return base.Channel.GetUpdatedPricesInDateTimeRangeAsync(authToken, fromDateTime, toDateTime, startId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfArgusOnline.GetCustomReportBinResponse> WcfArgusOnline.ArgusWSSoap.GetCustomReportBinAsync(WcfArgusOnline.GetCustomReportBinRequest request)
        {
            return base.Channel.GetCustomReportBinAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.GetCustomReportBinResponse> GetCustomReportBinAsync(string authToken, WcfArgusOnline.PriceReportParams pars)
        {
            WcfArgusOnline.GetCustomReportBinRequest inValue = new WcfArgusOnline.GetCustomReportBinRequest();
            inValue.authToken = authToken;
            inValue.pars = pars;
            return ((WcfArgusOnline.ArgusWSSoap)(this)).GetCustomReportBinAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.AuthenticationResult> AuthenticateAsync(string username, string password)
        {
            return base.Channel.AuthenticateAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.AuthenticationResult> Authenticate2Async(string username, string password, string pluginInstallID)
        {
            return base.Channel.Authenticate2Async(username, password, pluginInstallID);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.AuthenticationResult> Authenticate3Async(string username, string password, string pluginInstallID, string pluginVersion)
        {
            return base.Channel.Authenticate3Async(username, password, pluginInstallID, pluginVersion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfArgusOnline.GetTablesBinResponse> WcfArgusOnline.ArgusWSSoap.GetTablesBinAsync(WcfArgusOnline.GetTablesBinRequest request)
        {
            return base.Channel.GetTablesBinAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.GetTablesBinResponse> GetTablesBinAsync(string authToken, string[] tableNames)
        {
            WcfArgusOnline.GetTablesBinRequest inValue = new WcfArgusOnline.GetTablesBinRequest();
            inValue.authToken = authToken;
            inValue.tableNames = tableNames;
            return ((WcfArgusOnline.ArgusWSSoap)(this)).GetTablesBinAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetTablesAsync(string authToken, string[] tableNames)
        {
            return base.Channel.GetTablesAsync(authToken, tableNames);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.ArrayOfXElement> GetTablesLastUpdatedAsync(string authToken, string[] tableNames)
        {
            return base.Channel.GetTablesLastUpdatedAsync(authToken, tableNames);
        }
        
        public System.Threading.Tasks.Task<decimal[]> GetNewsListAsync(string authToken, System.DateTime dateFrom, System.DateTime dateTo, decimal[] categoryList, bool categoryiesListOr, decimal[] regionList, bool regionListOr)
        {
            return base.Channel.GetNewsListAsync(authToken, dateFrom, dateTo, categoryList, categoryiesListOr, regionList, regionListOr);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.NewsRecord> GetNewsStoryAsync(string authToken, decimal newsId)
        {
            return base.Channel.GetNewsStoryAsync(authToken, newsId);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.NewsRecordFull> GetNewsStoryByIdAsync(string authToken, decimal newsId)
        {
            return base.Channel.GetNewsStoryByIdAsync(authToken, newsId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfArgusOnline.GetNewsItemsByDateTimeResponse> WcfArgusOnline.ArgusWSSoap.GetNewsItemsByDateTimeAsync(WcfArgusOnline.GetNewsItemsByDateTimeRequest request)
        {
            return base.Channel.GetNewsItemsByDateTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfArgusOnline.GetNewsItemsByDateTimeResponse> GetNewsItemsByDateTimeAsync(string authToken, System.DateTime dateTimeFrom, System.DateTime dateTimeTo, System.Nullable<bool> free, System.Nullable<bool> featured, System.Nullable<decimal> languageId, System.Nullable<decimal> newsTypeId)
        {
            WcfArgusOnline.GetNewsItemsByDateTimeRequest inValue = new WcfArgusOnline.GetNewsItemsByDateTimeRequest();
            inValue.authToken = authToken;
            inValue.dateTimeFrom = dateTimeFrom;
            inValue.dateTimeTo = dateTimeTo;
            inValue.free = free;
            inValue.featured = featured;
            inValue.languageId = languageId;
            inValue.newsTypeId = newsTypeId;
            return ((WcfArgusOnline.ArgusWSSoap)(this)).GetNewsItemsByDateTimeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArgusWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ArgusWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ArgusWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.argusmedia.com/ArgusWSVSTO/ArgusOnline.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ArgusWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.argusmedia.com/ArgusWSVSTO/ArgusOnline.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ArgusWSSoap,
            
            ArgusWSSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.3.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
